### ISSUE TITLE
Support multiple resource selection for deployment

### ISSUE THREAD

**Issue by apupier** [camel-tooling/vscode-camelk#103]
currently only one resource is allowed when deploying a Camel K integration, it would be nice to allow using several of them.

Maybe split in two iterations (or pick only one?):
- allow multiple files selection in the file dialog
- have multiple steps in the command to add other files

see also what is done in #93

**Comment by bfitzpat** [comment]
Instead of prompting the user for a single file, then asking if there are more files, I like the idea of doing a multi-file selection in the file dialog. I ran with that in https://github.com/camel-tooling/vscode-camelk/pull/85 and now we can process multiple files using that approach.

**Comment by djelinek** [comment]
verified - Tooling for Apache Camel K by Red Hat (marketplace version 0.0.9)
