### ISSUE TITLE
No integration selection made

### ISSUE THREAD

**Issue by nicolaferraro** [camel-tooling/vscode-camelk#108]
I've upgraded to 0.7, created a groovy file, connected to a remote OCP 4 instance. When I right-click on the file and start a Camel K integration I get the two lines:

```
Starting new integration via Kamel executable.
Kamel execution return code: Error: No integration selection made.
```

Actually I get no popup that let me choose the kind of deployment. Any idea?

**Comment by apupier** [comment]
we discovered this issue yesterday. It is a regression between VS Code 1.37.1 and 1.38.0 which has been released yesterday :-(

**Comment by apupier** [comment]
duplicates of https://github.com/camel-tooling/vscode-camelk/issues/106

**Comment by apupier** [comment]
Version 0.0.8 with a fix is available on marketplace.
