### ISSUE TITLE
Add support for starting integrations with YAML file extension

### ISSUE THREAD

**Issue by jamesnetherton** [camel-tooling/vscode-camelk#112]
See example here:

https://github.com/apache/camel-k/blob/master/examples/routes.yaml

I could try to take a stab at implementing this.

**Comment by apupier** [comment]
I think it should be mainly to add yaml in the list https://github.com/camel-tooling/vscode-camelk/blob/cc0cbaae069d0eff1cd25d9dfcff17f47b03e06d/package.json#L132
And check that it is working...
(given that we have no tests for deployment yet :-( )
