### ISSUE TITLE
Provide visual hint of number of replicas for deployed integration

### ISSUE THREAD

**Issue by apupier** [camel-tooling/vscode-camelk#124]
The main interest is to know when it is scaled to 0.
So either display the number directly, or a different overlay with number as tooltip

We cannot display log when teh scale is to zero. So removing the contextual menu would be great (can be done in a different issue/PR if makes sense when implementing)

"for the scale / replicas feedback, for example a scaled to zero is displayed as running and querying the logs returns No deployed integration found for: rest-eventing"

**Comment by astefanutti** [comment]
apache/camel-k#962 exposes the `.status.replicas` field that can be relied on to get the number of replicas for an integration.
