### ISSUE TITLE
Improve message in Deployed Integration when Kubernetes user is logged out

### ISSUE THREAD

**Issue by apupier** [camel-tooling/vscode-camelk#125]
when the user is logged out, there is a message in the output `Refreshing Apache Camel K Integrations view using kubectl failed. Error: Error: Unauthorized`

**Comment by bfitzpat** [comment]
"Error: Unauthorized" is coming back from Kubernetes, so I'm not quite sure what we can do.

**Comment by apupier** [comment]
- provide a message in UI reporting the error or pointing to the error when connection is failing
- ask to Kubernetes community how to know if the user is logged or not. And if it doesn't exists, if it is possible to add this API
