### ISSUE TITLE
Enable changing/displaying the namespace 

### ISSUE THREAD

**Issue by bfitzpat** [camel-tooling/vscode-camelk#128]
From Antonin - 
> Support changing the namespace - also may be useful the display the current namespace somewhere and possibly the ability to switch namespace would be useful too

This is available from the kamel cli tool with the -n flag? 
>  -n, --namespace string   Namespace to use for all operations

Not sure how to set it however

**Comment by bfitzpat** [comment]
According to Antonin...

> Yes, you can use the --namespace option, both from kamel and kubectl CLIs, for all commands issued by the Camel K VS Code extension.
> 
> The CLIs otherwise rely the KUBECONFIG environment variable to source the default context that can reference the default namespace to use. This default context is set for example when running oc project <namespace>.
> 
> https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#the-kubeconfig-environment-variable
> 
> My understanding is that valuing the --namespace option would be enough, but that may be nice that the VS code extension relies on KUBECONFIG as well.

Will look at the kubeconfig options down the line, but I know that the Kubernetes extension includes some kubeconfig support. https://github.com/Azure/vscode-kubernetes-tools#working-with-kubeconfigs 

I believe we can leverage that now that we use that extension as a dependency.

**Comment by djelinek** [comment]
verified - redhat.vscode-camelk v0.0.10
