### ISSUE TITLE
Use kubernetes rest-api instead of direct kubectl calls

### ISSUE THREAD

**Issue by bfitzpat** [camel-tooling/vscode-camelk#14]
Currently we rely on locally available kamel and kubectl commands on the system path. It would be better to rely on the kubernetes rest API to provide more flexibility for accessing systems beyond the local box. 

Here's a link providing docs on Kubernetes' Rest API -  https://containerjournal.com/2018/12/27/introduction-to-using-the-kubernetes-rest-api/ 

It  looks like we may be able to delete an endpoint using rest -  https://docs.openshift.com/enterprise/3.0/rest_api/kubernetes_v1.html#delete-a-endpoints 

And get a list of pods https://docs.openshift.com/enterprise/3.0/rest_api/kubernetes_v1.html#list-or-watch-objects-of-kind-pod 

Not sure how to start a new integration using a rest call however. 

This will require additional configuration for the extension, such as the system URL and port to send these calls to -- as well as an adjustment in the way we process incoming data for the integrations view. Currently we hack the output provided in the terminal and the rest call will return json that should be easier to process.

**Comment by bfitzpat** [comment]
Considering that we un-register a running integration using "kubectl get integration" I'm not sure how that maps to a get call. I tried "curl -v http://localhost:8005/api/v1/namespaces/integration/pods" and that didn't work.

**Comment by bfitzpat** [comment]
As for other commands:
* stopping a running integration, we use "kamel delete <filename>" 
* starting a new integration, we use "kamel run --dev <filename>"

How do we map those back to kubernetes rest API calls?

**Comment by bfitzpat** [comment]
Once starting the kubernetes proxy: kubectl proxy –port=8000... this seems to work:

* curl -v http://localhost:8001/apis/camel.apache.org/v1alpha1/namespaces/default/integrations

It returns a lot of stuff, but part of it is the JSON containing the running integrations on the system being pinged by the get:

```
* Expire in 0 ms for 6 (transfer 0x2339130)
* Expire in 1 ms for 1 (transfer 0x2339130)
* Expire in 0 ms for 1 (transfer 0x2339130)
* Expire in 2 ms for 1 (transfer 0x2339130)
*   Trying ::1...
* TCP_NODELAY set
* Expire in 149994 ms for 3 (transfer 0x2339130)
* Expire in 200 ms for 4 (transfer 0x2339130)
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 149994 ms for 3 (transfer 0x2339130)
* Connected to localhost (127.0.0.1) port 8001 (#0)
> GET /apis/camel.apache.org/v1alpha1/namespaces/default/integrations HTTP/1.1
> Host: localhost:8001
> User-Agent: curl/7.64.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Length: 3150
< Content-Type: application/json
< Date: Tue, 28 May 2019 19:34:35 GMT
<
{"apiVersion":"camel.apache.org/v1alpha1","items":[{"apiVersion":"camel.apache.org/v1alpha1","kind":"Integration","metadata":{"creationTimestamp":"2019-05-28T19:34:25Z","generation":1,"name":"context","namespace":"default","resourceVersion":"1974525","selfLink":"/apis/camel.apache.org/v1alpha1/namespaces/default/integrations/context","uid":"99c2fc61-817f-11e9-b332-00155d009d12"},"spec":{"sources":[{"content":"\u003c?xml version=\"1.0\" encoding=\"UTF-8\"?\u003e\r\n\u003c!--\r\n    Licensed to the Apache Software Foundation (ASF) under one or more\r\n    contributor license agreements.  See the NOTICE file distributed with\r\n    this work for additional information regarding copyright ownership.\r\n    The ASF licenses this file to You under the Apache License, Version 2.0\r\n   
 (the \"License\"); you may not use this file except in compliance with\r\n    the License.  You may obtain a copy of the License at\r\n         http://www.apache.org/licenses/LICENSE-2.0\r\n    Unless required by applicable law or agreed to in writing, software\r\n    distributed under the License is distributed on an \"AS IS\" BASIS,\r\n    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\r\n    See the License for the specific language governing permissions and\r\n    limitations under the License.\r\n--\u003e\r\n\u003croutes xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\r\n        xmlns=\"http://camel.apache.org/schema/spring\"\r\n        xsi:schemaLocation=\"\r\n            http://camel.apache.org/schema/spring\r\n            http://camel.apache.org/schema/spring/camel-spring.xsd\"\u003e\r\n\r\n    \u003croute id=\"hello\"\u003e\r\n        \u003cfrom uri=\"timer:hello?period=3s\"/\u003e\r\n      
  \u003csetBody\u003e\r\n            \u003cconstant\u003eGoodbye Camel-K demo!\u003c/constant\u003e\r\n        \u003c/setBody\u003e\r\n        \u003cto uri=\"log:info\"/\u003e\r\n    \u003c/route\u003e\r\n\r\n\u003c/routes\u003e\r\n","name":"context.xml"}]},"status":{"camelVersion":"2.23.2","context":"jvm","dependencies":["camel:core","runtime:jvm"],"digest":"vy9NBbdjSN7TGVuslTZ7XU73f9AikPrXzGAbmACbtLjA","image":"10.104.255.220/default/camel-k-jvm:769","phase":"Running","runtimeVersion":"0.3.2"}},{"apiVersion":"camel.apache.org/v1alpha1","kind":"Integration","metadata":{"creationTimestamp":"2019-05-28T19:24:31Z","generation":1,"name":"my","namespace":"default","resourceVersion":"1973792","selfLink":"/apis/camel.apache.org/v1alpha1/namespaces/default/integrations/my","uid":"37d2e689-817e-11e9-b332-00155d009d12"},"spec":{"sources":[{"content":"from('timer:tick?period=3s')\r\n  .setBody().constant('Hello world from Camel K')\r\n  .to('log:info')\r\n  ","name":"my.groovy"}]},"status":{"camelVersion":"2.23.2","context":"groovy","dependencies":["camel:core","runtime:groovy","runtime:jvm"],"digest":"vYdonLBeuE-LjzNB8s2KQMgn7AmCk6vQKvlhFDkYYZPI","image":"10.104.255.220/default/camel-k-groovy:771","phase":"Running","runtimeVersion":"0.3.2"}}],"kind":"IntegrationList","metadata":{"continue":"","resourceVersion":"1974546","selfLink":"/apis/camel.apache.org/v1alpha1/namespaces/default/integrations"}}
* Connection #0 to host localhost left intact
```

**Comment by bfitzpat** [comment]
Will investigate adding some settings for the extension to allow users to either use the kubectl method or the rest API method for retrieving the list of deployed integrations from the running kubernetes system. That will allow us to use either method going forward.

**Comment by bfitzpat** [comment]
The PR https://github.com/camel-tooling/vscode-camelk/pull/26 offers all the functionality I was hoping to get into this issue, which is the ability to do everything we did using the command-line utilities in the system path (kubectl/kamel) via proxied Rest calls to a running Kubernetes system.

**Comment by bfitzpat** [comment]
Merged PR - will continue to work on minor issues encountered, but the functionality is there

**Comment by bfitzpat** [comment]
Essentially, the user should be able to do the same tasks with the minikube/camel-k local command line tools as they can with the rest APIs...
* list existing integrations
* create a new integration
* stop a running integration
* follow an integration log

**Comment by djelinek** [comment]
verified with master branch
