### ISSUE TITLE
Update readme with new settings and changed proxy/namespace options

### ISSUE THREAD

**Issue by bfitzpat** [camel-tooling/vscode-camelk#167]
Now that we are relying on the CLIs and have removed the rest API settings, and updated the namespace support, we need to also update the readme with the new options.

**Comment by bfitzpat** [comment]
Updated thru https://github.com/camel-tooling/vscode-camelk/pull/168 and https://github.com/camel-tooling/vscode-camelk/pull/169

**Comment by djelinek** [comment]
verified with master branch
