### ISSUE TITLE
Camel K integrations view does not refresh

### ISSUE THREAD

**Issue by nicolaferraro** [camel-tooling/vscode-camelk#18]
I'm using a real cluster, not minikube (so much more delay).

When I run a integration, the "CAMEL K INTEGRATIONS" view does not update, unless I hit refresh manually. Also if I remove the integration from the list, I need to hit refresh again.

**Comment by bfitzpat** [comment]
Interesting. I'm currently exploring using the kubernetes proxy so I can do rest "get" calls to retrieve the integration list rather than using kubectl, but I'll see if I can build in a refresh timer for long-running operations so it refreshes the view every few seconds.

**Comment by bfitzpat** [comment]
Revamped the refresh so that it tries a few times before bailing. If we need to increase the number of retries, we definitely can or we can make it configurable. 

https://github.com/camel-tooling/vscode-camelk/pull/22

**Comment by bfitzpat** [comment]
Updated in latest 0.0.3 version -- please give it a shot and let me know if we need to increase the number of retries
