### ISSUE TITLE
[Blocker]Master is failing on Jenkins "Failed to run testsFailed"

### ISSUE THREAD

**Issue by apupier** [camel-tooling/vscode-camelk#185]
build started to fail between the 10 and 15 October

https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/vscode-camelk-release/133/

`Failed to run testsFailed`

the only commit was: https://github.com/camel-tooling/vscode-camelk/commit/8e2e2bb3eb26c005fab34fbe00e0b18683c7826b

**Comment by bfitzpat** [comment]
Not sure why this is failing - everything builds ok on Travis-ci? Will investigate first thing next week

**Comment by apupier** [comment]
Travis is not looking to test reports. Jenkins is looking at it.

**Comment by bfitzpat** [comment]
So apparently jenkins can't ping http://www.google.com. It's failing at this test it seems? https://github.com/camel-tooling/vscode-camelk/blob/b2fc5e94232c5ad225cbf56837e5e889163f9f75/src/test/suite/camelkjsonutils.test.ts#L56

Should we change it to https?

**Comment by bfitzpat** [comment]
@apupier looks like all tests pass now on Jenkins, but it's not generating the test report and still reporting the build as a failure - https://dev-platform-jenkins.rhev-ci-vms.eacng.rdu2.redhat.com/job/vscode-camelk-release/139/

**Comment by apupier** [comment]
in the pointed commit that introduced the issue, the way to launch test has been modified.
https://github.com/camel-tooling/vscode-camelk/commit/8e2e2bb3eb26c005fab34fbe00e0b18683c7826b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R178

seems the parameter mocha-jenkins-reporter https://github.com/camel-tooling/vscode-camelk/commit/8e2e2bb3eb26c005fab34fbe00e0b18683c7826b#diff-64bb3acdbe97e7252804e3679319ecdcL21 is not available in the index.ts file https://github.com/camel-tooling/vscode-camelk/commit/8e2e2bb3eb26c005fab34fbe00e0b18683c7826b#diff-dc2baeab65c75197ed216bfc054a39f2

**Comment by bfitzpat** [comment]
https://github.com/camel-tooling/vscode-camelk/pull/188 did fix it - we're now green on jenkins again the https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/vscode-camelk-release/145/

**Comment by djelinek** [comment]
closing - jenkins job is green
