### ISSUE TITLE
No output when running an integration

### ISSUE THREAD

**Issue by nicolaferraro** [camel-tooling/vscode-camelk#19]
The doc says it runs in '--dev' mode and display the output but it's not the case (I've tried it with groovy). Using dev mode also deletes the integration when closing the terminal, which is not desired imo.

But the doc should be changed or the log displayed in output.

**Comment by bfitzpat** [comment]
There is output. If you go to View->Output and select "Camel-K" in the drop-down list, you can see everything. I will add that to the readme.

**Comment by bfitzpat** [comment]
@nicolaferraro I have added a bit of documentation here to show how to open the Output channel for running integrations - https://github.com/camel-tooling/vscode-camelk#start-camel-k-integration-menu-results

**Comment by bfitzpat** [comment]
Resolved
