### ISSUE TITLE
Generate quickstart

### ISSUE THREAD

**Issue by nicolaferraro** [camel-tooling/vscode-camelk#20]
It would be nice to have some quickstarts generated. E.g. 
I want to write a groovy integration, I hit (somewhere) "Camel K -> New Groovy Integration" and a timer to log is created.

I'm not using VSCode during normal dev, so don't know the best way to present this to users.

**Comment by bfitzpat** [comment]
Definitely something to explore!

**Comment by bfitzpat** [comment]
Investigating adding this functionality through the didact work we've started - https://github.com/camel-tooling/vscode-camelk/pull/217

**Comment by bfitzpat** [comment]
Chatted with @nicolaferraro . We're going to wait for the `init` command in the next `kamel` release so we can initialize new files with quickstarts consistent with what the runtime is providing. 

We will look to add this functionality for groovy, java, javascript, xml, and yaml for the first go-round.

**Comment by nicolaferraro** [comment]
The `kamel init` command is available in 1.0.0-RC2.

**Comment by bfitzpat** [comment]
@nicolaferraro do we have any docs on the `kamel init` command somewhere? I looked in the readme and https://camel.apache.org/camel-k/latest/index.html and not seeing anything I can use on how that works? Is there a particular Git or JIRA issue that has examples of it in action?

**Comment by nicolaferraro** [comment]
Forgot to add it to the general doc.

Usage is simple:
```
kamel init XXX.java
```

creates a file name `XXX.java' with the boilerplate and a simple hello world integration that the user can then edit.

The content provided is based on the file extension, so it works also with `.yaml`, `.xml`, `.groovy` etc..

**Comment by bfitzpat** [comment]
Awesome. That should work nicely. I'll start pondering how to get that integrated on the tooling side. Thanks @nicolaferraro !

**Comment by apupier** [comment]
this has been implemented few months ago. See https://issues.redhat.com/browse/FUSETOOLS2-139
