### ISSUE TITLE
Improve release process to include sources when publishing vsix

### ISSUE THREAD

**Issue by nickboldt** [camel-tooling/vscode-camelk#243]
Similar to discussions in...

* https://github.com/camel-tooling/vscode-wsdl2rest/issues/142 
* https://github.com/redhat-developer/vscode-java/issues/892
* https://github.com/redhat-developer/vscode-project-initializer/issues/40
* https://github.com/redhat-developer/vscode-quarkus/issues/177
* https://github.com/windup/rhamt-vscode-extension/issues/263
* https://issues.redhat.com/browse/FUSETOOLS2-80

... we'd like that each release of this .vsix file to dl.jb.o be accompanied by a matching sources.tar.gz

I don't care if you push the .vsix to GH releases page, or tar up sources and push that to dl.jb.o, just that we have binary and sources in the same place.

Thanks!

This is a RH product security requirement in that we need to either build everything used in CodeReady Workspaces from scratch as part of our build, or else provide matching sources for upstream RH-built binaries.

**Comment by apupier** [comment]
related PR https://github.com/camel-tooling/vscode-camelk/pull/254

**Comment by djelinek** [comment]
closing - verified with master branch, sources available at update site
