### ISSUE TITLE
Configure Sonar analysis

### ISSUE THREAD

**Issue by apupier** [camel-tooling/vscode-camelk#27]
currently failing with 

```
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 38.367s
INFO: Final Memory: 29M/100M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
ERROR: You're not authorized to run analysis. Please contact the project administrator.
```

**Comment by apupier** [comment]
provided the SONAR_TOKEN generated from https://sonarcloud.io/account/security/ on travis configuration https://travis-ci.org/camel-tooling/vscode-camelk/settings as explained in travis doc https://docs.travis-ci.com/user/sonarcloud/#inspecting-code-with-the-sonarqube-scanner

it pushes the result analysis successfully:
https://sonarcloud.io/dashboard?id=vscode-camelk
![image](https://user-images.githubusercontent.com/1105127/59850499-b42a5380-936a-11e9-97a0-9dee7af5990d.png)

 there are 0 issues detected so might worth double-checking that the analysis is correctly configured

**Comment by apupier** [comment]
there are 244 lines of code scanned
![image](https://user-images.githubusercontent.com/1105127/59850597-eb006980-936a-11e9-8f85-8492439b5b86.png)

so seems well scanned.

Code coverage is a more complicated task to setup on VSCode extensions tests.

**Comment by bfitzpat** [comment]
Thanks @apupier !
