### ISSUE TITLE
When activating extension, verify version on install

### ISSUE THREAD

**Issue by bfitzpat** [camel-tooling/vscode-camelk#270]
Discovered a bug -- though we may check to see if we get back a version, we're not actually validating that the version is the most recent. 

This needs to change 
https://github.com/camel-tooling/vscode-camelk/blob/0658af265a1c1c54b25121cb443afdcbffbb02c0/src/extension.ts#L367

We are not actually checking the version returned -- just that there IS a version returned.

**Comment by bfitzpat** [comment]
The workaround is to delete the `kamel` executable in /.config/Code/User/globalStorage/redhat.vscode-camelk/camelk/tools/kamel

**Comment by djelinek** [comment]
verified - redhat.vscode-camelk 0.0.14-413 _(snapshot)_, VS Code 1.43.2
