### ISSUE TITLE
Provide user a way to circumvent the auto-upgrade of Kamel CLI version installation

### ISSUE THREAD

**Issue by bfitzpat** [camel-tooling/vscode-camelk#280]
With https://github.com/camel-tooling/vscode-camelk/pull/274, it was discussed that that PR ensures that every time the extension activates, it updates the kamel CLI to the latest version as specified in the installer.ts file (https://github.com/camel-tooling/vscode-camelk/blob/146d02527cba00469fd717497f234eb82b10285e/src/installer.ts#L34). It does not ask, it just updates the cli. 

This is fine as the default until we come to cases where the latest CLI may not work on a particular platform. Perhaps it won't quite work on Che as expected with a particular version and needs to be downgraded to an older one. That should be a valid case. 

As I point out in the PR, the only thing I can think is to offer another preference that essentially says "turn off automatic update of CLI" and works around the version check. If the user checks the box (which is unchecked by default), the installer avoids the auto-update.

**Comment by bfitzpat** [comment]
Another possibility is to raise the preference -- so the user can explicitly specify which version of the CLI to install. Perhaps an editable field that shows the version currently used (defaults to the one specified as noted above) and will attempt to download the version the user specifies if it is overridden.

**Comment by bfitzpat** [comment]
Created https://issues.redhat.com/browse/FUSETOOLS2-208 to track this in JIRA as well

**Comment by bfitzpat** [comment]
Adding an "Autoupdate" checkbox. This does a couple of things to keep the version in check.

1. The version will always update to the latest default value set in the extension (right now 1.0.0-RC2)
2. If the user changes the version, but leaves autoupdate checked, it will reset it to the latest default.
3. If the user turns off autoupdate and then changes the version, the version they set sticks.
4. If they then turn on autoupdate, the version goes back to the default (1.0.0-RC2)

![image](https://user-images.githubusercontent.com/530878/75724174-09a95500-5c9b-11ea-9e86-987b4eb7c4bc.png)

Note that the user must restart the workspace (and they get a little info popup saying that the version has changed and they need to restart) to get the version of the runtime they specify. 

Also note that there's a chance that the Camel K CLI version can get out of whack with what is installed in a particular runtime (Kubernetes, OpenShift). At this time there's no way for the user to see the difference, but perhaps that's something we should look into?

Also note that we don't verify that the version is available currently, so that should happen as well.

**Comment by bfitzpat** [comment]
@lhein I have added the new autoupgrade checkbox and the logic there. I am having issues figuring out a good way to ping a HTTPS path (such as this one at github that works "https://github.com/apache/camel-k/releases/download/1.0.0-RC1/camel-k-client-1.0.0-RC1-linux-64bit.tar.gz") -- I have a placeholder "pingGithubUrl" method to do this, but nothing I have tried has worked well. 

To clarify what I'm after... this one for a fictitious "RCX" should not work: https://github.com/apache/camel-k/releases/download/1.0.0-RCX/camel-k-client-1.0.0-RCX-linux-64bit.tar.gz

But the "https://github.com/apache/camel-k/releases/download/1.0.0-RC2/camel-k-client-1.0.0-RC2-linux-64bit.tar.gz" should.

**Comment by bfitzpat** [comment]
Found a way to handle it using cross-fetch (https://www.npmjs.com/package/cross-fetch) but have a test failing...

```
  42 passing (37s)
  1 failing
  1) ensure install methods are functioning as expected
       ensure cli version checking works correctly:
      AssertionError [ERR_ASSERTION]: cli version checking, negative case worked
      + expected - actual
      -false
      +true

  	at /home/travis/build/camel-tooling/vscode-camelk/out/src/test/suite/install.test.js:70:24
```

**Comment by apupier** [comment]
closing as the issue was marked as resolve several months ago
