### ISSUE TITLE
Move to Red Hat publisher

### ISSUE THREAD

**Issue by apupier** [camel-tooling/vscode-camelk#29]
- remove publish from Travis config
- change icon
- change publisher in package.json
- provide jenkins pipeline config

see also https://github.com/camel-tooling/camel-lsp-client-vscode/issues/107

**Comment by bfitzpat** [comment]
Done - extension now available here https://marketplace.visualstudio.com/items?itemName=redhat.vscode-camelk

**Comment by djelinek** [comment]
verified with master branch
