### ISSUE TITLE
Add ability to get metadata about running integrations

### ISSUE THREAD

**Issue by bfitzpat** [camel-tooling/vscode-camelk#30]
In addition to being able to see the running log for a running integration, it would be great to get some kind of metadata about the integration. 

Per Claus: "another idea is to have some kind of dashboard with all the integrations in the namespace ala syndesis so you can see number of messages processed / failed etc"

**Comment by apupier** [comment]
wouldn't it be something generic to all Camel deployment in OpenShift? not only with Camel-K?

**Comment by bfitzpat** [comment]
Maybe? I don't honestly know what kind of data we can get from a running integration at this point. Something to explore.

**Comment by bfitzpat** [comment]
Added a basic "status" indicator (Running, Building Kit, Error, etc.) for running integrations here - https://github.com/camel-tooling/vscode-camelk/pull/57
