### ISSUE TITLE
close the log view when the integration is stopped

### ISSUE THREAD

**Issue by lhein** [camel-tooling/vscode-camelk#310]

**Comment by bfitzpat** [comment]
I'm wondering if this should be optional. Are there cases where waiting to see if a camel log shuts down without errors is a benefit? Especially with https://github.com/camel-tooling/vscode-camelk/issues/311 fixed, there's a lot more in that log around watching integrations spin up and shut down when they are updated.

**Comment by apupier** [comment]
agree.
Maybe having a marker to show that the integration corresponding to the log has been stopped would be enough? Italic title? a suffix in the title such as [stopped]?

we can still imagine a settings to automatically close the view? Either one in VS Code or a checkbox on the log view?

**Comment by bfitzpat** [comment]
I will see if we can watch for the items in the log to appear and update the title of the window accordingly. That's a good idea.

It appears that we may be able to simply dispose the panel (i.e. `Extensions can also programmatically close webviews by calling dispose() on them` from https://code.visualstudio.com/api/extension-guides/webview#lifecycle) that I hadn't seen before. I will see what we can do to leverage that and add a setting.

**Comment by bfitzpat** [comment]
Addressed both issues with https://github.com/camel-tooling/vscode-camelk/pull/316

**Comment by djelinek** [comment]
verified - redhat.vscode-camelk 0.0.14-413 _(snapshot)_, VS Code 1.43.2
