### ISSUE TITLE
log view can become stale on integration updates

### ISSUE THREAD

**Issue by lhein** [camel-tooling/vscode-camelk#311]
if the pod changes on an update of the integration then the old log view becomes stale and a new one needs to be opened which has a different title.

**Comment by bfitzpat** [comment]
Looks like we can use the kamel cli to follow logs so this doesn't occur. 

i.e. `kamel log [myintegration]` will update the pod when you redeploy the integration and continues scrolling the log

**Comment by bfitzpat** [comment]
Created https://github.com/apache/camel-k/issues/1283

**Comment by bfitzpat** [comment]
Created https://github.com/camel-tooling/vscode-camelk/pull/313

**Comment by djelinek** [comment]
verified - redhat.vscode-camelk 0.0.14-413 _(snapshot)_, VS Code 1.43.2
