### ISSUE TITLE
no easy way to open the operator log or logs for individual integration kits

### ISSUE THREAD

**Issue by bfitzpat** [camel-tooling/vscode-camelk#321]
Two of the the logs that would be very helpful when debugging integration issues would be the Camel K Operator log and any log associated with a particular Camel K integration kit. Though you can get to them through the Kubernetes view, it would be nice if we could provide a short cut to get to them via the Integrations view.

**Comment by bfitzpat** [comment]
Adding a new command button to the integrations view with the Note icon from https://github.com/microsoft/vscode-icons 
![image](https://user-images.githubusercontent.com/530878/75190143-ea478080-570c-11ea-974b-21283c4ce2a1.png)

![image](https://user-images.githubusercontent.com/530878/75190320-49a59080-570d-11ea-86b8-e5ad769b0fc5.png)

**Comment by djelinek** [comment]
verified - redhat.vscode-camelk 0.0.14-413 _(snapshot)_, VS Code 1.43.2
