### ISSUE TITLE
error messages sometimes have "Error" duplicated

### ISSUE THREAD

**Issue by bfitzpat** [camel-tooling/vscode-camelk#325]
when clicking on "Open Apache Camel K Operator log" although the deployment has not been done yet. The error message is starting with 2 "Error" word. `Error Error from server (BadRequest): container "camel-k-operator" in pod "camel-k-operator-6bcf77ddf8-llmp4" is waiting to start: ContainerCreating`

**Comment by bfitzpat** [comment]
Created https://github.com/camel-tooling/vscode-camelk/pull/326. Simple fix.

**Comment by djelinek** [comment]
verified - redhat.vscode-camelk 0.0.14-413 _(snapshot)_, VS Code 1.43.2
