### ISSUE TITLE
Provide an error message to user when connection failed

### ISSUE THREAD

**Issue by apupier** [camel-tooling/vscode-camelk#33]
currently there is a log in debug console of the host VS Code (which won't be available to a normal user)

for information, it is this error:

```
Command string: kubectl get integration
CamelKNodeProvider.js:208
[ERROR] Unable to connect to the server: dial tcp 192.168.1.31:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
CamelKNodeProvider.js:216
[CLOSING] 
```

**Comment by bfitzpat** [comment]
This has been resolved with the latest changes in https://github.com/camel-tooling/vscode-camelk/pull/46

We now ping the kamel and kubernetes rest APIs the same way when refreshing the Camel-K Integrations view. While updating the view, we put a message in the status bar so there's some indication of activity. If we are unable to get data, we put the error in the Camel-K output channel. If we get data, we populate the view.

**Comment by djelinek** [comment]
verified - Tooling for Apache Camel K by Red Hat (marketplace version 0.0.9)
