### ISSUE TITLE
Add ability to configure the proxy port value

### ISSUE THREAD

**Issue by bfitzpat** [camel-tooling/vscode-camelk#34]
Currently the proxy port is included as the proxy URL setting, but it would be useful to spin that off as a separate setting so we also have it available for the "Start the kubectl proxy server" command.

**Comment by bfitzpat** [comment]
Added new setting here - https://github.com/camel-tooling/vscode-camelk/pull/47

**Comment by bfitzpat** [comment]
* Camel-K extension settings - proxyURL now doesn't include the port by default
* Camel-K extension settings - new setting proxyPort is appended to the proxyURL
* Some clean-up in the utilities around generating the URLs
* Some additional tests added for URL construction
* Some clean-up in the extension code around setting defaults and URL construction
* One minor fix for the "go" kubernetes utility test for Windows where we replace any Windows-style CRLF for comparisons

Biggest thing to test is the proxy URL -- make sure that when useProxy is set and the proxy URL & port are set, everything still works when the user starts the proxy server locally (optional) or is using a remote proxy

**Comment by djelinek** [comment]
verified - Tooling for Apache Camel K by Red Hat (marketplace version 0.0.9)
