### ISSUE TITLE
Improve camelk.integrations.startproxy command

### ISSUE THREAD

**Issue by apupier** [camel-tooling/vscode-camelk#38]
currently, you need to first update the preferences for url and to tell to use it or not.
it would be nice that the command is asking for the url parameter (providing by default the value in preference) and propose to change the preference value to "use the proxy" in case it is not enabled, indicating what are the implications otherwise.

**Comment by bfitzpat** [comment]
Just to clarify a few things...
* We default to using the local command-line tools. 
* If the local command-line tools aren't installed, starting the local proxy won't work. 
* We have no idea what the proxy URL will be for a Kubernetes or OpenShift environment.

I'm not quite sure what you are proposing here?
* Defaulting to "use the proxy" set to true? 

Can you clarify a bit @apupier ?

**Comment by apupier** [comment]
When using the "Start proxy command", it might fail because you have not configured the settings for the proxy url/port. These parameters needs to be asked when using the command. 

> we have no idea what the proxy URL will be for a Kubernetes or OpenShift environment

it means that it is even more important to ask user when he/she tries to use the command proxy. It is impossible to guess that we need to configure it in the settings.

Also, even if I start the proxy, it is still no t used. I also need to go to settings to say "use the proxy". At the end of the command execution, if the "use the proxy" is set to false, i think we should warn user/allow him/her to set to true.

**Comment by bfitzpat** [comment]
No longer needed, since we removed the proxy option
