### ISSUE TITLE
Find better way to re-publish routes

### ISSUE THREAD

**Issue by bfitzpat** [camel-tooling/vscode-camelk#45]
Currently we have the ability to:
* Deploy a new integration
* View the log for the running integration
* Delete the integration (which closes the Output for the log if one is open)

But what happens in a slightly more complex case? Let's say we want to:
* Deploy an integration
* View the log for the running integration
* Update the route for the integration and re-deploy (new)
* Delete the integration

Right now if we update the integration and re-deploy we gain additional artifacts. Out of date Output channels for logs for pods that are shut down remain open. 

We need to decide what the best approach is here because this will be a common use case.

We are not listening for changes to the file currently because deploying via the executable operates in a slightly different way than deploying via the Rest APIs in Kubernetes. Since we are managing the deployment JSON, we are not taking advantage of the connection I have seen between the running integration just magically *updating* when saved in the file system. And we don't really have an explicit link between the file name and the deployed integration, though that information is available in the deployment descriptor for the integration.

Is it enough to simply be smarter about re-deploying the integration and cleaning up the older Output channels?

**Comment by apupier** [comment]
it is the kind of issues that odo and OpenShift Connector VS Code extension project are working on. Would be interesting to reach them, and/or to reuse what they are doing.

**Comment by bfitzpat** [comment]
Approach I'm considering now...

* take the filename of the camel file we're running via Camel-K
* remove the extension
* change to Kebab case (similar to https://github.com/apache/camel-k/blob/master/pkg/util/kubernetes/sanitize.go, which is what they're doing)
* look for the pod that uses that integration name (already have code for this)
* remove the old output channel
* proceed with deployment -- it seems that camel-k is smart enough to remove the old version first

**Comment by bfitzpat** [comment]
Fun fact, I've discovered an issue with the latest version of Kubernetes and Minikube with Camel-K...
```
I used to be able to get the pod name for a running integration via: kubectl get pods | grep {integrationName}
but now with minikube 1.2.0 and kubernetes version 1.15.0 I am not seeing any of the deployed integrations as pods any longer
I see them in the custom resources/integrations list
but I don't seem to be able to get the log for a custom resource
this was working with minikube 1.1.1 and kubernetes version 1.12.0 and seems to be new behavior
```

**Comment by bfitzpat** [comment]
Found a good example of the Kebab case fix for Javascript - https://gist.github.com/thevangelist/8ff91bac947018c9f3bfaad6487fa149

**Comment by bfitzpat** [comment]
Created https://github.com/camel-tooling/vscode-camelk/pull/46 to start work on this issue.

Currently the PR removes the output channel if the integration has already been published. (It also cleaned up some code, removing some duplicated areas and streamlining the approach.)

This is a work in progress and I want to have it also re-open the new output channel if the integration is being re-published. 

Might also add a new setting that automatically opens the output channel for a new integration.

**Comment by apupier** [comment]
> * change to Kebab case (similar to https://github.com/apache/camel-k/blob/master/pkg/util/kubernetes/sanitize.go, which is what they're doing)

if we don't reuse it directly (i guess it is not available as a library), we will need to write non-regression test checking that they have not changed the implementation.

**Comment by bfitzpat** [comment]
> if we don't reuse it directly (i guess it is not available as a library), we will need to write non-regression test checking that they have not changed the implementation.

@apupier At best, any test we write will be an approximation since we can't call it directly, but I can do that.

**Comment by apupier** [comment]
> > if we don't reuse it directly (i guess it is not available as a library), we will need to write non-regression test checking that they have not changed the implementation.
> 
> @apupier At best, any test we write will be an approximation since we can't call it directly, but I can do that.

maybe we can add a test upstream?
or we can pull the dependency in some way?

**Comment by bfitzpat** [comment]
Can we call Go from inside TypeScript (see the "node" section here - https://medium.com/learning-the-go-programming-language/calling-go-functions-from-other-languages-4c7d8bcc69bf)

**Comment by bfitzpat** [comment]
This has been resolved with  https://github.com/camel-tooling/vscode-camelk/pull/46

**Comment by djelinek** [comment]
verified - Tooling for Apache Camel K by Red Hat (marketplace version 0.0.9)
