### ISSUE TITLE
Remove the `Follow kit builder log` menu

### ISSUE THREAD

**Issue by bfitzpat** [camel-tooling/vscode-camelk#450]
With the 1.0.0 release of Camel K, the kit builder no longer operates as a pod. We used to be able to access the kit pod directly and grab the log from kubernetes, but now that's not the case.

According to Nicola:

> I think the kit builder follows the logs of the pod that is supposed to build the kit image, right? There's no counterpart of that functionality in the kamel CLI iirc
> On minikube we now default to using a special builder that does not create an external pod, to improve performance
> It uses the same behaviour that was already the default on openshift where the maven build was already done inside the operator pod
> in general the platform->status->build->strategy = [pod | routine] tells you if there'll be a builder pod
> we default to "routine" on both openshift and minikube now

And currently there isn't a clean way to get to that log:

> Currently logs are just appended to the operator logs and cannot be filtered

For now, we can still see the kit/operator log messages in the operator log (button on the Apache Camel K Integrations view toolbar labeled `Open Apache Camel K Operator Log`). 

We should remove the `kit log` menu and action and clean up the Readme/Didact tutorial until we determine if that functionality should be re-added in the future.

**Comment by bfitzpat** [comment]
https://github.com/camel-tooling/vscode-camelk/pull/451

**Comment by apupier** [comment]
closing as the issue was marked as resolve several months ago
