### ISSUE TITLE
namespace setting not being applied to kamel calls

### ISSUE THREAD

**Issue by bfitzpat** [camel-tooling/vscode-camelk#489]
if you change the default namespace setting in the user settings for the camel k extension, it should pick it up for all kamel calls but it doesn't appear to be -- need to research and see what's going on there

**Comment by bfitzpat** [comment]
It appears we are also not taking namespace into account when we create configmaps and secrets, so we need to look into that as well.

**Comment by apupier** [comment]
created JIRA issue where issues are better tracked https://issues.redhat.com/browse/FUSETOOLS2-572

**Comment by apupier** [comment]
The namespace setting was applied. It was the log message which was wrong. This is fixed. See  https://issues.redhat.com/browse/FUSETOOLS2-572 for more details
