### ISSUE TITLE
Propose to automatically download kubectl if not present

### ISSUE THREAD

**Issue by apupier** [camel-tooling/vscode-camelk#49]

**Comment by bfitzpat** [comment]
We will get this for free if we depend on the Kubernetes extension being present as an extension dependency (see https://github.com/camel-tooling/vscode-camelk/issues/65)

**Comment by bfitzpat** [comment]
Resolved as part of the work done for https://github.com/camel-tooling/vscode-camelk/issues/50

**Comment by djelinek** [comment]
verified - redhat.vscode-camelk (0.0.10)
