### ISSUE TITLE
Propose to automatically download kamel executable if not present

### ISSUE THREAD

**Issue by apupier** [camel-tooling/vscode-camelk#50]

**Comment by apupier** [comment]
even more important if going with Kamel only way of doing see #104

**Comment by bfitzpat** [comment]
Can we perhaps leverage https://github.com/Azure/vscode-kubernetes-tools/blob/0b35bdcaf4f0687180aa38f908cf1e1ed33bc7e3/src/components/installer/installer.ts#L13 ?

Maybe use/reformat to install the Camel K cli?

**Comment by djelinek** [comment]
verified - redhat.vscode-camelk (0.0.10)
