### ISSUE TITLE
che: Camel K wrong url

### ISSUE THREAD

**Issue by rbaumgar** [camel-tooling/vscode-camelk#534]
When I try to use Camel K samples in Che I get following error

`
Activating extension 'Tooling for Apache Camel K by Red Hat' failed: Camel K CLI Version v1.1.0 unavailable. Please check the Apache Camel K version specified in VS Code Settings. Inaccessible url: https://github.com/apache/camel-k/releases/download/v1.1.0/camel-k-client-v1.1.0-linux-64bit.tar.gz
`

plugin loaded: vscode-camelk:latest 

Correct url is:
https://github.com/apache/camel-k/releases/download/v1.1.0/camel-k-client-1.1.0-linux-64bit.tar.gz (without "v" in the filename)

This happens even when I have in my preferences: Camel K: Integrations Runtime Version: 1.0.1

**Comment by apupier** [comment]
Can you specify which version of Che you are using? also, which version of VS Code Camel K in Che plugin registry you are using please?

**Comment by rbaumgar** [comment]
che: 7.17.2 or crw_master 2.3.0.GA 
vscode-camelk: 0.15

**Comment by apupier** [comment]
I don't reproduce on che.openshift.io which is also using 7.17.2 and VS Code Camel K 0.0.15.

It is surely related to https://github.com/camel-tooling/vscode-camelk/issues/500 which is fixed in VS Code Camel K 0.0.16

**Comment by apupier** [comment]
> This happens even when I have in my preferences: Camel K: Integrations Runtime Version: 1.0.1

Potential workarounds to be tested:
- in settings to mention version 1.0.1 and to uncheck the "Camelk> Integrations: Auto Upgrade"
- modify [plugin registry](https://github.com/redhat-developer/codeready-workspaces/blob/362f9d3093ac12e711c6e30156785f7c42601e99/dependencies/che-plugin-registry/v3/plugins/redhat/vscode-camelk/0.0.15/meta.yaml#L19) to use https://download.jboss.org/jbosstools/vscode/stable/vscode-camelk/vscode-camelk-0.0.16-698.vsix
- modify devfile and use a "reference" on an updated version of the plugin [meta.yaml](https://github.com/redhat-developer/codeready-workspaces/blob/2.3.0.GA/dependencies/che-plugin-registry/v3/plugins/redhat/vscode-camelk/0.0.15/meta.yaml) pointing to https://download.jboss.org/jbosstools/vscode/stable/vscode-camelk/vscode-camelk-0.0.16-698.vsix

technical investigation:
Check content of the image registry.redhat.io/codeready-workspaces/plugin-kubernetes-rhel8:2.3 https://quay.io/repository/crw/plugin-kubernetes-rhel8?tab=tags
https://github.com/redhat-developer/codeready-workspaces/blob/2.3.0.GA/dependencies/che-plugin-registry/v3/plugins/redhat/vscode-camelk/0.0.15/meta.yaml#L15 (need to find where is hosted the source code)

I'm guessing that it contains a not expected kamel executable version.

(no CodeReady Workspaces available for now)

**Comment by apupier** [comment]
> strange I tried it on che as well. now it works on che with Camel K 0.0.15
> But it still does not work on Codeready Workspaces 2.3.

thanks, I reported an issue against CodeReady Workspaces https://issues.redhat.com/browse/CRW-1197

**Comment by rbaumgar** [comment]
changed back to Camel K 0.0.13. works wieh CodeReady Workspaces

**Comment by apupier** [comment]
The problem has been marked as resolved for next CodeReady Workspace release, which will be version 2.5.0

thanks for having reported it!
