### ISSUE TITLE
Handle deployment via camel-k command line executable with --dev option set

### ISSUE THREAD

**Issue by bfitzpat** [camel-tooling/vscode-camelk#56]
We had this in the very first version where everything was output to the same output channel. It would be good to have it as an option to show all the good details in that console to the Camel-K output channel if the --dev flag is set. 

We would need a way to turn the --dev option off as well, or just indicate that the user should re-run the integration or delete it to stop the --dev mode.

**Comment by bfitzpat** [comment]
According to Nicola: 
> you can try kamel run --logs --sync integration.groovy and it should not get deleted when you exit the command, instead of --dev

**Comment by bfitzpat** [comment]
Added new option with https://github.com/camel-tooling/vscode-camelk/pull/91

**Comment by bfitzpat** [comment]
New option in drop-down 
![Screenshot from 2019-08-29 13-55-17](https://user-images.githubusercontent.com/530878/63972014-125b6d00-ca65-11e9-8684-b7ad4a036cba.png)

Runs the file in --dev mode and redirects ALL output to the Apache Camel K output channel
![Screenshot from 2019-08-29 13-55-31](https://user-images.githubusercontent.com/530878/63972058-27d09700-ca65-11e9-84f7-a3031d5c6395.png)

Updating the file automatically redeploys it. Removing the integration from the Integration View stops it.

**Comment by paoloantinori** [comment]
hey @bfitzpat this is great!
anything else that needs to be done on this or would it be okay to  mark it as done?

**Comment by bfitzpat** [comment]
Hasn't been merged yet and there's some discussion as to whether the default (i.e. the first item in the list) should be Basic or Dev Mode (see https://github.com/camel-tooling/vscode-camelk/pull/91)

**Comment by djelinek** [comment]
verified - Tooling for Apache Camel K by Red Hat (marketplace version 0.0.9)
