### ISSUE TITLE
Investigate auto-refresh of integrations view

### ISSUE THREAD

**Issue by bfitzpat** [camel-tooling/vscode-camelk#58]
Now that we are adding decorators to the Camel-K Integrations view that update on refresh, it would be good to set an auto-refresh cycle so the user wouldn't have to manually click the Refresh button to see changes. (https://github.com/camel-tooling/vscode-camelk/issues/55#issuecomment-517593459)

**Comment by djelinek** [comment]
verified - Tooling for Apache Camel K by Red Hat (marketplace version 0.0.9)
