### ISSUE TITLE
Windows user Dir with spaces causes "path with spaces" "not recognized as a" internal or external command,

### ISSUE THREAD

**Issue by josersleal** [camel-tooling/vscode-camelk#588]
If the User directory has a space then the extension crashes with:
exaample user directory in windows: 'c:\Users\Name Name2"

Error: 'c:\Users\Name' is not recognized as an internal or external command,
operable program or batch file.
    at Socket.<anonymous> ("Path...".vscode\extensions\redhat.vscode-camelk-0.0.17\out\src\kamel.js:97:32)    at Socket.emit (events.js:228:7)    at addChunk (_stream_readable.js:309:12)    at readableAddChunk (_stream_readable.js:286:13)    at Socket.Readable.push (_stream_readable.js:224:10)    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)

t.log | @ | console.ts:70
-- | -- | --
  | $logExtensionHostMessage | @ | extHostTunnelService.ts:43
  | _doInvokeHandler | @ | rpcProtocol.ts:372
  | _invokeHandler | @ | rpcProtocol.ts:372
  | _receiveRequest | @ | rpcProtocol.ts:253
  | _receiveOneMessage | @ | rpcProtocol.ts:185
  | (anonymous) | @ | rpcProtocol.ts:51
  | fire | @ | event.ts:584
  | fire | @ | ipc.net.ts:459
  | _receiveMessage | @ | ipc.net.ts:792
  | (anonymous) | @ | ipc.net.ts:647
  | fire | @ | event.ts:584
  | acceptChunk | @ | ipc.net.ts:216
  | (anonymous) | @ | ipc.net.ts:137
  | t | @ | ipc.net.ts:859
  | emit | @ | events.js:223
  | addChunk | @ | _stream_readable.js:309
  | readableAddChunk | @ | _stream_readable.js:290
  | Readable.push | @ | _stream_readable.js:224
  | onStreamRead | @ | internal/stream_base_commons.js:181

**Comment by apupier** [comment]
Thanks for the report.
created https://issues.redhat.com/browse/FUSETOOLS2-813 for easier planification in Red Hat integration team

**Comment by apupier** [comment]
see https://github.com/camel-tooling/vscode-camelk/pull/601

**Comment by apupier** [comment]
forgot to close this issue. it is fixed with 0.0.19
