### ISSUE TITLE
Decorate status of deployed integrations (rest)

### ISSUE THREAD

**Issue by bfitzpat** [camel-tooling/vscode-camelk#60]
Follow-up to https://github.com/camel-tooling/vscode-camelk/issues/55

This works for the local kubectl/kamel case but does not yet work for Proxied Rest calls.

**Comment by bfitzpat** [comment]
Ended up being a very minor fix - https://github.com/camel-tooling/vscode-camelk/pull/61

**Comment by djelinek** [comment]
verified - Tooling for Apache Camel K by Red Hat (marketplace version 0.0.9)
