### ISSUE TITLE
Investigate further use of Kubernetes API as a dependency

### ISSUE THREAD

**Issue by bfitzpat** [camel-tooling/vscode-camelk#65]
Investigate using the k8s api available thru NPM at https://github.com/Azure/vscode-kubernetes-tools-api as well as using the VS Code Kubernetes extension from Microsoft (https://marketplace.visualstudio.com/items?itemName=ms-kubernetes-tools.vscode-kubernetes-tools)

Need to determine:
* does declaring a transitive dependency on the VS Code Kubernetes extension work? Does it automatically install it? 
* if our extension depends on the k8s extension, and kubectl binaries are not installed, does the k8s extension offer a way to download it?

It seems to hint at it at the end of this section https://github.com/Azure/vscode-kubernetes-tools#dependencies :

> We recommend you install these binaries on your system PATH before using the extension. If these binaries aren't on your system PATH, then some commands may not work. If the extension needs one of the core Kubernetes tools and it's missing, it will offer to install it for you.

**Comment by bfitzpat** [comment]
Adding this to the package.json
```
    "extensionDependencies": [
        "ms-kubernetes-tools.vscode-kubernetes-tools"
	],	
```
and trying to install the Camel-K extension presents this error, so it does look like one extension will drag in the other. 

![image](https://user-images.githubusercontent.com/530878/62724393-21a04b00-b9d0-11e9-873e-270dba352a00.png)

**Comment by bfitzpat** [comment]
As far as installing the kubectl executable under the covers, it seems to be doing that as well. After ensuring that ALL versions of kubectl are out of my path and getting the extension installed, it appears to use the one in users\[username]\.vs-kubernetes\tools\kubectl

![image](https://user-images.githubusercontent.com/530878/62734274-d98c2300-b9e5-11e9-97c2-7a288caa649a.png)

**Comment by bfitzpat** [comment]
```
Installing kubectl...
Installing Helm...
Installing Draft...
Installing Minikube...
Done
```

**Comment by bfitzpat** [comment]
It appears to install 1.15.2, which is the most recent version (https://storage.googleapis.com/kubernetes-release/release/stable.txt)

```
 ~/.vs-kubernetes/tools/kubectl
$ ./kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}

```

**Comment by bfitzpat** [comment]
The only problem is the combination of versions does not currently work with Camel-K 1.0.0-M1... 

By default, it pulls in the latest stable versions --
* kubectl 1.15.2
* minikube 1.3.0

Camel-K 1.0.0-M1 locally will only work for me with:
* kubectl 1.15.1
* minikube 1.1.1

**Comment by bfitzpat** [comment]
We now install and use the kubectl/kamel CLIs at startup and depend on the Kubernetes exension.

**Comment by djelinek** [comment]
verified - redhat.vscode-camelk v0.0.10
