### ISSUE TITLE
Avoid refreshing Camel-K integrations view on startup if view is collapsed

### ISSUE THREAD

**Issue by apupier** [camel-tooling/vscode-camelk#67]
I noticed it because I don't have "kamel" and the error
```
Refreshing Camel-K Integrations view using kubectl failed. Error: 'kamel' is not recognized as an internal or external command,
operable program or batch file. 
```
is logged.

but it seems reasonable to never do it when the view is collapsed and only call it when the view is expanded.

**Comment by bfitzpat** [comment]
Fixed with https://github.com/camel-tooling/vscode-camelk/pull/83

**Comment by djelinek** [comment]
verified - Tooling for Apache Camel K by Red Hat (marketplace version 0.0.9)
