### ISSUE TITLE
kamel cli download not working on windows

### ISSUE THREAD

**Issue by nanomad** [camel-tooling/vscode-camelk#769]
Extension version: 0.0.25

On windows, `getDownloadURLForCamelKTag` uses win32 as the platform name, but download links contain `windows-64bit` instead.

Since version checking is mandatory, the extension cannot start.

**Comment by apupier** [comment]
Thanks for the report

nota: I created https://issues.redhat.com/browse/FUSETOOLS2-1140 for Red Hat team to look at it

**Comment by nanomad** [comment]
Looking at the code, the same applies to camel-k on MacOS: platform name is `darwin`, but download links have `mac`

**Comment by apupier** [comment]
the constants https://github.com/camel-tooling/vscode-camelk/blob/6abf3fec07ec7a07c2c773de57b8cc6450ebc314/src/shell.ts#L22-L24 should be different for `kamel` and `kubectl`. Currently, the same are used.

**Comment by nanomad** [comment]
Considering that the kubectl does some "renaming" for windows already (win32 -> windows) I think the best approach could be:
- Use an enum in platform detection code (shell.ts)
- Have `kubectl` translate them one way
- Have `kamel` translate them another way

If that's OK I can provide a quick PR

**Comment by apupier** [comment]
> If that's OK I can provide a quick PR

of course, this is very welcome

**Comment by nanomad** [comment]
PR Submitted: https://github.com/camel-tooling/vscode-camelk/pull/770
