### ISSUE TITLE
Remove dependency to vscode-commons

### ISSUE THREAD

**Issue by fbricon** [camel-tooling/vscode-camelk#793]
https://github.com/camel-tooling/vscode-camelk/blob/1133357e02422d8a73ceaec079b85b9f16da933a/package.json#L369

See https://github.com/redhat-developer/vscode-redhat-telemetry#how-to-use-this-library and [YAML](https://github.com/redhat-developer/vscode-yaml/pull/528/files) integration as an example

**Comment by apupier** [comment]
corresponding issue in Red Hat tracker https://issues.redhat.com/browse/FUSETOOLS2-1154

**Comment by apupier** [comment]
@fbricon why there is the need to provide a `configuration`?
https://github.com/redhat-developer/vscode-yaml/pull/528/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R77

it means that now each extension has its own configuration property? Or by using the same id, the configuration properties will be "merged"?

**Comment by fbricon** [comment]
Yes, we'll see duplicates until the next vscode release. See https://github.com/microsoft/vscode/issues/124662.
After that release settings will be merged

**Comment by apupier** [comment]
see https://github.com/camel-tooling/vscode-camelk/pull/807

**Comment by apupier** [comment]
done via https://github.com/camel-tooling/vscode-camelk/pull/844 will eb available in next release (0.0.26)
