### ISSUE TITLE
Support deploy of Camel K integration mixing different options

### ISSUE THREAD

**Issue by apupier** [camel-tooling/vscode-camelk#95]
currently (and with what is coming) you have to choose between:
- no config
- config map
- secret
- property
- resource
- devmode

but in fact i think we need to be able to provide a mix of them.

Handling it with a command palette action might be difficult, maybe time to think to provide launch task or a more advanced wizard if user is selecting an "advanced" deployment.

**Comment by apupier** [comment]
https://code.visualstudio.com/api/extension-guides/task-provider

**Comment by bfitzpat** [comment]
https://github.com/camel-tooling/vscode-camelk/pull/302

**Comment by apupier** [comment]
see https://issues.redhat.com/browse/FUSETOOLS2-215

**Comment by djelinek** [comment]
verified - redhat.vscode-camelk 0.0.14-413 _(snapshot)_, VS Code 1.43.2
